### PR TITLE
Structure files and add a taskrunner

### PR DESCRIPTION
**Pull request by HoverBaum**
This request makes two proposals:
#1 Structure files in folder

For this I propose to have a `src` folder with a structure like this for now.

```
.
├── css
│   └── ice.css
├── html
│   └── icebg.html
├── img
│   └── icon128.png
├── js
│   ├── icebg.js
│   ├── icepage.js
│   ├── icepageold.js
│   └── jquery-2.2.2.min.js
└── manifest.json
```

This takes the files as they were before and organizes them into folder arrcording to what they do. An approach like this will come in handy once the project grows larger. You could imagine the "js" folder having subfolders for certains tasks or background scripts. With that it will be easy to find the files you want to modify.
#2 [Gulp](http://www.gulpjs.com/) as a taskrunner

A taskrunner runs tasks for you. They do all the things we don't want to do manually. In this case I would propose to use it to minify files. And also to create a .zip file for the store.

The adventage here is that we will be able to provide a smaller download to users. Getting used to task automation would also be a great learning experience for people new to web-dev.

### CODE REVIEW

**Comment by HoverBaum** [comment]
Might be interesting for [Deployment Question](https://github.com/kyrofox/iceproject/issues/8).

**Comment by GrimTheReaper** [comment]
+1

**Comment by HoverBaum** [comment]
Wrote up a piece on why and what Gulp and got it to work properly.

With this the entire extension goes from 50KB to 43KB in size.

I think the main point here is to introduce people to principles that will be valuable for bigger projects. Interested to hear what @kyrofox thinks about this.

**Comment by ghost** [comment]
> I think the main point here is to introduce people to principles that will be valuable for bigger projects.

I like this idea. I wanted to learn about task runners myself.

**Comment by kyrofox** [comment]
I'll be merging this in because I do want to use something for minifying code, and this seems like a great option. Also, I like how you've set up the new file structure, and it's cool to have a source folder (as long as we can run directly from it w/o compiling first), as well as a complete deployment folder. It just seems cleaner that way.

**Comment by kyrofox** [comment]
I just made a bunch of changes to file struct so this will be a bitch. I'm going to make some changes to master for this first to minimize conflicts.

**Comment by kyrofox** [comment]
Alright! Should be good soon, but lets chat on discord to completely resolve this so it works with the current files and such.

PM me on discord whenever you have time! Thanks!

**Comment by HoverBaum** [comment]
Needed to refactore two lines to get the uglification to work properly. Should be fine now though and ready to be merged.

**Comment by kyrofox** [comment]
Awesome! Thank you, merged.

**Pull request merged**
