### PR TITLE
CSS style

### PR DESCRIPTION
**Pull request by ghost**
The default CSS file was kinda messy. So I did the following:
- Fixed incorrect properties values;
- Added missing vendor-specific properties;
- Toned down z-index values;
- No "px" units in zero values;
- No attribute selectors (they are slow);
- Fixed spacing;
- Rules organized by sections;
- Comments on main rules.

### CODE REVIEW

**Comment by kyrofox** [comment]
Thank you dude, this is awesome. I'm going to test this and then pull.

**Comment by kyrofox** [comment]
Tested. Looks good. Great job this is really sick. I wasn't aware of some of this. I see the changes you made are generally:
Comments
Removing weird CSS
Made things more consistent

Am I missing anything, or are there any specific things you want to point out that you noticed? I'm not that good at CSS, so it would be cool to hear your opinion on this.

**Comment by ghost** [comment]
Other than incorrect values, missing vendor properties and absurd z-index numbers, I changed no values. But I would recommend you to use relative sizes like "em" or "rem" instead of "px". One could also argue that using ID selectors is not recommended, as it makes the style too coupled with the page structure.

**Comment by ghost** [comment]
You can also check the [Can I Use](http://caniuse.com/) website to see which browser are compatible with a certain property. I know this is a chrome extension only for now, but it's good to be prepared.

**Pull request merged**
