### PR TITLE
[WIP] Javascript Style

### PR DESCRIPTION
**Pull request by ghost**
The changes:
- Indentation using two spaces instead of tabs;
- Trailing spaces are no more;
- "icebg.html" formatted to be valid HTML5;
- Added "TODO" comments where applicable
- All JavaScript code is approved by my [Google JavaScript Style](https://google.github.io/styleguide/javascriptguide.xml) linter.
#### What is this Google thing?

**TL;DR**: all JavaScript files now use single quotes for strings, have no lines bigger than 80 characters and use four spaces of indentation when breaking the arguments of a function in new lines.

### CODE REVIEW

**Comment by HoverBaum** [comment]
I feel there should be a bigger discussion about which style to follow. I for one am a big fan of tabs instead of spaces because you don't have to have the 2 vs. 4 discussion. People can just set that locally.

We could also consider to follow [Airbnbs JS style gide](https://github.com/airbnb/javascript) which is nicer to read and comes with an JSLint file or use [StandardJS](https://github.com/feross/standard) even though I don't like their "2 spaces" thing.

Just to put a few more options out there.

**Comment by ghost** [comment]
I also think we should define a style to follow. This pull request is a suggestion, I can change the commits to whatever we end up choosing.

There are a lot of different styles out there. I chose the Google one because... well because it's Google, and it seems to be the most recommend one.

About the indentation, I only used 2 spaces because of the Google style. I have no preference, as it is trivial to map the tab key to input spaces, or to convert the spaces to tabs and set them to a different width. The only important thing is the indentation to be consistent inside the project.

However it would be essential the chosen style to have a linter. I don't want to have to memorize all the rules.

I want to hear @kyrofox thoughts on this.

**Comment by ghost** [comment]
Rebase to add a missing TODO comment and to put the "icebg.html" commit at the end.

**Comment by Willsr71** [comment]
Most other languages dictate 4 spaces and according to w3schools [it is the same is for JavaScript](http://www.w3schools.com/js/js_conventions.asp). One reason I can imagine Google chose to go with 2 spaces as the norm is that a good number of people do not minify their JavaScript so [it can save space in such situations](http://stackoverflow.com/questions/22782677/coding-style-in-javascript-why-prefer-2-spaces-not-4-spaces).

That being said, my vote is for 4 spaces if we do decide on spaces and not tabs.

**Comment by kyrofox** [comment]
This is a 2000 line delta PR. Judging by the first 500 lines I checked and I still need to verify with the other 1500), I'm not seeing many major changes except line spaces and rewriting comments. What did you change exactly?

**Comment by ghost** [comment]
Well, it's mostly indentation and spacing: two spaces for indentation, 4 spaces when breaking function arguments in multiple lines, and no lines are over 80 characters long. Strings are now `'single quote'` instead of `"double quote"`. There's also `//TODO` comments indicating sections that need to be worked. They are a convention used by programmers.

There are few code changes where  `object["property"]` became `object.property` and `else { if {//code}}` became `else if {//code}`.

I mostly just edited the code until my Google linter stopped complaining. There are no behavior changes in this pull request, the code will execute the same way. You can execute `git diff --ignore-all-space` to see the differences while ignoring all white-space. In this mode the first commit will show no differences.

**Comment by ghost** [comment]
I also propose that we use [ESLint](http://eslint.org/) as the linter of choice for our style. My last commit ads a `.eslintrc.json` configuration file as example. [It can be used later with the Gulp task runner](https://github.com/adametry/gulp-eslint).

**Comment by ghost** [comment]
I'm closing this PR due the community not wanting to follow a code style, as said on Discord.

**Comment by kyrofox** [comment]
Hey Tiso. I apologize for not replying sooner. To be completely honest, I've been frustrated about PRs/requests for style changes, and I haven't figured out how to reply correctly, but I've been thinking about it a lot. I still don't really know what to say, but this is probably as close as I'll get. My original goal for the project was for a bunch of us to just get together and make things; and not to get bogged down in making things AROUND the core features for user. It was my fault in not providing a better direction towards what this application would be, but it's never too late for that. So, it's not that I don't want style, I just wanted everyone to share the same direction I had, more specifically along the lines of disregarding whatever was wrong and just **doing** things, making cool shit, and having fun. I really tried my best to not take PR's about style personally, but even when I took them as being constructive, I just wasn't having fun anymore, and I got bored.

I still don't know what to do about this PR because it is all in a single commit, and because the indentation change makes it so I don't know what exactly is changed without reading the whole thing, and even that allows for human error (if I make a mistake) in seeing the changes.

**Pull request closed without merging**
