### PR TITLE
CSS Patch

### PR DESCRIPTION
**Pull request by ghost**
The default CSS file was kinda messy, so I did the following:
- Fixed wrong property values;
- Added missing vendor specific properties ;
- Toned down all the z-index values;
- Removed "px" unit in zero values;
- Removed attribute selectors (they are slow);
- Better spacing, no trailing white space;
- Organized the rules in logical sections;
- Commented on the main rules.

### CODE REVIEW

**Comment by GrimTheReaper** [comment]
Looks like you might want to rebase. You have commits in your PR that don't belong to the requested change and would end up dirtying up the commit history.

**Comment by ghost** [comment]
Oh right. I'll be right back.

**Comment by GrimTheReaper** [comment]
You could have rebased without closing the PR :P

**Comment by ghost** [comment]
Sorry, I'm new to GitHub pull requests.

**Pull request closed without merging**
